Change getAll permission checking.
digitalbazaar/bedrock-ldn-inbox pull request #2
Opened 2017-02-16 22:10 UTC by mattcollier

I expect this is a pattern that we will be applying elsewhere.  I wonder if we should add a permission check before the query to determine if the user has PERMISSIONS.LDN_INBOX_ACCESS for any resource at all .
If we do not, a user with no permissions at all will be able to cause the API to return/filter the entire collection just to return [].  We need to figure out what proper protections should be put in place in the HTTP for this reason as well.

2017-02-17 18:25 UTC, mattcollier commented on lib/index.js
> +    callback(null, results.getAuthorized);
We have discussed that it's not a good idea to return a full record.  The getAll endpoint has previously been restricted to admin level permissions.  We are allowing the caller to specify fields to this API, do we want to restrict those fields to properties contained in `inbox` in this case?

2017-02-17 19:38 UTC, dlongley commented on lib/index.js
> +    callback(null, results.getAuthorized);
We don't want to do the restriction here, but we can do it at the HTTP level. It's up to the caller to make sure that the fields are appropriately restricted, i.e. they shouldn't let the actor pick any fields they want.

2017-02-21 22:51 UTC, dlongley requested changes

2017-02-21 22:51 UTC, dlongley commented on lib/index.js
> +  // meta is required for permission check, if meta was
I think you accidentally your sentence

2017-02-21 22:51 UTC, dlongley commented on lib/index.js
> +    // check to make sure the caller is allowed to access the documentType
`documentType` should be `inbox`?

2017-02-21 22:51 UTC, dlongley commented on lib/index.js
> +    // (Note: fields *must not* have excluded `documentType.id` in this
`documentType.id` => `inbox.id`

2017-02-21 22:51 UTC, dlongley commented on lib/index.js
> +    fields.meta = true;
If we're doing this with `meta` -- why not also do it with `id` (which we also need for the permission check below).

2017-02-21 22:51 UTC, dlongley commented on lib/index.js
> +          resource: record.meta,
The resource isn't `record.meta` ... I find this confusing. It should be `record.inbox.id`. If we've already pulled out `meta`, we can just use a list: `resource: [record.inbox.id, record.meta.owner]` and don't use `translate`.

2017-02-21 22:51 UTC, dlongley commented on lib/index.js
> +          excludeId: true
We can remove this comment and `excludeId` if we use a resource list above that includes the owner and remove translate.

2017-02-22 16:13 UTC, mattcollier commented on lib/index.js
> +    fields.meta = true;
Added a todo.

2017-02-22 16:15 UTC, mattcollier commented
@dlongley ready for another pass.

2017-02-22 18:59 UTC, dlongley approved these changes

2017-02-22 19:08 UTC, merged